# Generated by Django 3.1.3 on 2020-12-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20201202_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueEntrada',
            fields=[
            ],
            options={
                'verbose_name': 'estoque saida',
                'verbose_name_plural': 'estoque saida',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('estoque.estoque',),
        ),
    ]
