# Generated by Django 3.1.3 on 2020-12-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_estoqueentrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueSaida',
            fields=[
            ],
            options={
                'verbose_name': 'estoque saida',
                'verbose_name_plural': 'estoque saida',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('estoque.estoque',),
        ),
        migrations.AlterModelOptions(
            name='estoqueentrada',
            options={'verbose_name': 'estoque entrada', 'verbose_name_plural': 'estoque entrada'},
        ),
    ]
